title: GEDbpedia - online global encyclopedic database
description: GEDbpedia, is a free online global encyclopedic database (similar to IMDb and Wikipedia) for articles about celebrities and people, facts and trivia, books, companies, games, and much more.
theme: jekyll-theme-midnight
